stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: python:latest
  before_script:
    - pip install -r test_requirements.txt
  script:
    - python -m pytest drugs_shooting_list

build:
  stage: build
  image: python:3.7
  before_script:
    - apt update && apt install zip
  script:
    - export zip_path=$(pwd)
    - python drugs_shooting_list/parser/load.py
#    - python -m drugs_shooting_list.func_test_result_json
    - mv results.json drugs_shooting_list
    - zip --exclude test_*.py --exclude *.pyc --exclude *.txt -r ${zip_path}/${ZIP_NAME} drugs_shooting_list yc_functions.py
    - pip install -r requirements.txt --root requirements
    - cd requirements/usr/local/lib/python3.7/site-packages/
    - zip --exclude *.pyc -ur ${zip_path}/${ZIP_NAME} *
  artifacts:
    when: on_success
    paths:
    - ${ZIP_NAME}
    expire_in: 10 mins
  only:
    - master
    - tags

yc_deploy:
  stage: deploy
  image: python:latest
  variables:
    function_name: main-messages-handler
    runtime: python37
    entrypoint: yc_functions.message_handler
    memory: 128m
    execution_timeout: 5s
    data_file_path: "/function/code/drugs_shooting_list/results.json"
  before_script:
    - pip install awscli
    - curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh --output install.sh
    - bash install.sh -n -i /opt/yandex-cloud
  script:
    - aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
    - aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
    - aws configure set region ru-central1
    - aws s3 --endpoint-url=https://storage.yandexcloud.net cp ${ZIP_NAME} s3://${BUCKET_NAME}
    - /opt/yandex-cloud/bin/yc config set token "$YC_OAUTH"
    - /opt/yandex-cloud/bin/yc serverless function version create
      --function-name ${function_name}
      --folder-id ${FOLDER_ID}
      --runtime ${runtime}
      --entrypoint ${entrypoint}
      --memory ${memory}
      --execution-timeout ${execution_timeout}
      --package-bucket-name ${BUCKET_NAME}
      --package-object-name ${ZIP_NAME}
      --description ${CI_COMMIT_SHORT_SHA}
      --environment TOKEN=${TOKEN}
      --environment ADMIN_UID=${ADMIN_UID}
      --environment DATA_FILE_PATH=${data_file_path}
  only:
    - master
    - tags
