stages:
  - build
  - deploy

build:
  stage: build
  image: python:latest
  script:
    - pip install awscli
    - zip ${zip_name} -r drugs_shooting_list requirements/* yc_functions.py
    - aws --endpoint-url=https://storage.yandexcloud.net \
        s3 cp ${zip_name} s3://${bucket_name}/${zip_name}
  only:
    - master
  artifacts:
    when: on_success
    paths:
    - ${zip_name}
    expire_in: 10 mins

yc_deploy:
  stage: deploy
  script:
    - curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh --output install.sh
    - sudo bash install.sh -n -i /opt/yandex-cloud
    - yc config set token $YC_OAUTH
    - yc serverless function version create
      --function-name=main-messages-handler
      --runtime python37
      --entrypoint yc_functions.message_handler
      --memory 128m
      --execution-timeout 1s
      --package-bucket-name ${bucket_name}
      --package-object-name ${zip_name}
  only:
    - master
    expire_in: 1 hour
